version: '3'

services:
  app.prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: 'prod-spa-stage'
    image: javi98/vue-test-client-prod:1.0.0
    container_name: vue-test-client-app-prod
    ports:
      - '85:80'